In [ ]:
##1)Write a program to create a 5 dimensional array with all zeros and ones

In [1]:
import numpy as np
zeros_array=np.zeros((1,1,1,5,4))
ones_array=np.ones((1,1,1,5,4))

print("Zeros Array:")
print(zeros_array)


print("Ones Array:")
print(ones_array)

Zeros Array:
[[[[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]]]]
Ones Array:
[[[[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]]]


In [ ]:
##2)Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)


In [ ]:
import numpy as np
zeros=np.zeros(10)
ones=np.ones(10)
fives=np.full(np.shape((3,10)),5)
array = np.concatenate((np.zeros(10), np.ones(10), np.full(10, 5)))
print(array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [ ]:
# 3)Write a program to create a 3x4 matrix filled with values from 10 to 21.


In [2]:
import numpy as np
np.arange(10,22).reshape(3,4)


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
# 4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,


In [ ]:
import numpy as np
matrix=np.zeros((10,10))
np.fill_diagonal(matrix,np.arange(10))
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [ ]:
# 5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.


In [5]:
x=np.arange(1,17).reshape(4,4)
y=x[:,::-1]
print(x)
print()
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
# 6)Write a program to reverse an array (the first element becomes the last).Given array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [ ]:
from numpy.lib import arraypad
array =  [12 ,13 ,14 ,15 ,16 ,17 ,18, 19 ,20 ,21, 22 ,23, 24 ,25 ,26 ,27 ]
reversed_array = array[::-1]
print(reversed_array)

[27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]


In [ ]:
 # 7 )Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100



In [ ]:
array=np.arange(1,101).reshape(10,10)
element_array= array[(array>30)& (array<80)& (array%5==0)]
print(element_array)

[35 40 45 50 55 60 65 70 75]


In [ ]:
# 8 )Write a program to create a 2D array with 1 on the border and 0 inside.


In [ ]:
x=np.ones((5,5))
print("original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 9) Write a program to create a checkerboard pattern .Don't use default array function
#Checkerboard pattern:
#[[0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]
 #[0 1 0 1 0 1 0 1]
 #[1 0 1 0 1 0 1 0]
 #[0 1 0 1 0 1 0 1]
 #[1 0 1 0 1 0 1 0]


In [6]:
l=[]
for i in range(0,64):
    a=i/8
    if(a%2==0):
        if(i%2==0):
            l.append(1)
        else:
            l.append(0)
    else:
        if(i%2==0):
            l.append(0)
        else:
            l.append(1)

x=np.array(l).reshape(8,8)
print(x)

[[1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [ ]:
# 10) Write a program to find common values between two arrays.
#Expected Output:
#array1: [10 20 40 60]
#array2: [10, 30, 40,50]


In [ ]:
array1 = [10,20,40,60]
array2 = [10,30,40,50]
common_values=[]
for num in array1:
  if num in array2:
      common_values.append(num)
print(common_values)

[10, 40]


In [ ]:
# 11Write a program to create an array 2d array and then reshape into 1d array



In [ ]:
two_dim_array=np.array([[1,2,3,4],[5,6,7,8],[14,15,16,17]])
one_dim_array=two_dim_array.flatten()
print("original 2D array:")

print(two_dim_array)

print("\nReshaped 1D array:")
print(one_dim_array)


original 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [14 15 16 17]]

Reshaped 1D array:
[ 1  2  3  4  5  6  7  8 14 15 16 17]


In [ ]:
#12 Write a user defined function for creating a 1 or 2d array from scratch without using array functions


In [13]:
def ndarray(x):
    n=int(input("enter the dimension: "))
    if type(x)==list or type(x)==tuple:
        c=len(x)
    if n==1:
        print("array({})".format(x))
    elif(n==0):
        m=int(l[0])
        print("array({})".format(m))
    elif (n==2):

        if(len(x[0])>1):
            print("array([",end="")
            for i in range(c):
                print("[{}]".format(x[i]))
            print("])")
        else:
            new=[]
            for i in x:
                if (i.isdigit()):
                    z=int(i)
                    new.append(z)
            print("array([{}])".format(new))
    else:
        pass
l=[]
n=int(input("enter the range: "))
for i in range(n):
    num=input("enter the elements: ")
    l.append(num)
print(l)
ndarray(l)



enter the range: 6
enter the elements: 1
enter the elements: 2
enter the elements: 3
enter the elements: 4
enter the elements: 5
enter the elements: 6
['1', '2', '3', '4', '5', '6']
enter the dimension: 2
array([[1, 2, 3, 4, 5, 6]])
